/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ATM;

import Controller.ATMController;
import Model.Card;
import static View.Manager.AddUser.encodeBase64String;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class ATMFrame extends javax.swing.JFrame {

    /**
     * Creates new form ATMGUI
     */
    public ATMFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("ATM BIDV");
            Image image = null;
            try {
                File f = new File("logoBIDV.jpg");
                image = ImageIO.read(f);
                BufferedImage resizedImage = new BufferedImage(lbLogo.getWidth(), lbLogo.getHeight(), BufferedImage.TYPE_INT_RGB);
                Graphics2D graphics2D = resizedImage.createGraphics();
                graphics2D.drawImage(image, 0, 0, lbLogo.getWidth(), lbLogo.getHeight(), null);
                graphics2D.dispose();
                lbLogo.setIcon(new ImageIcon(resizedImage));
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        
        
    }
    
    public void getCardInfo(List<Card> listCard){
        lbFullName.setText("Xin chào "+listCard.get(0).getNameBoss());
        nameBoss = listCard.get(0).getNameBoss();
        cardID=listCard.get(0).getId();
    }
    
    public void viewBlance(){
        ATMController a = new ATMController();
        viewblace = new ViewBlance(this,rootPaneCheckingEnabled);
        viewblace.getBlance(a.ViewBlance(cardID));
        viewblace.setVisible(true);
    }
    
    public BigInteger checkBlance() {
        ATMController a = new ATMController();
        return a.ViewBlance(cardID);
    }
 
    public void rutTien(BigInteger money){
        ATMController atm = new ATMController();
        if(atm.RutTien(cardID, money)){
            JOptionPane.showMessageDialog(this, "Rút tiền thành công !");
            withdraw.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Thất bại!");
            withdraw.dispose();
        }
    }
    
    public void changePin(int newpin){
        ATMController atmc = new ATMController();
        if(atmc.ChangePin(cardID, newpin)){
            JOptionPane.showMessageDialog(this, "Đổi mã pin thành công!");
            changePinDiaLog.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Đổi mã pin thất bại!");
        }
    }
     
    public void transferMoney(BigInteger receiver_cardID, BigInteger money){
        ATMController atmc = new ATMController();
        String note = nameBoss+" chuyen khoan";
        if(atmc.Transfer(cardID, receiver_cardID, money, note)){
            JOptionPane.showMessageDialog(this, "Chuyển khoản thành công.");
            transfer.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Chuyển khoản thất bại!");
        }
        
    }
    
    public void ViewHistoryTransaction() {
        ATMController a = new ATMController();
        transactionHistory = new TransactionHistory(this, rootPaneCheckingEnabled);
        transactionHistory.getHistoryTransaction(a.ViewHistoryTransaction(cardID));
        transactionHistory.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn3 = new javax.swing.JPanel();
        lbFullName = new javax.swing.JLabel();
        btnRutTien = new javax.swing.JButton();
        btnViewBlane = new javax.swing.JButton();
        btnChangPin = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbFullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbFullName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFullName.setText("Xin chào");

        btnRutTien.setText("Rút tiền");
        btnRutTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutTienActionPerformed(evt);
            }
        });

        btnViewBlane.setText("Vấn tin tài khoản");
        btnViewBlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBlaneActionPerformed(evt);
            }
        });

        btnChangPin.setText("Đổi PIN");
        btnChangPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangPinActionPerformed(evt);
            }
        });

        btnTransfer.setText("Chuyển khoản");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NGÂN HÀNG ĐẦU TƯ VÀ PHÁT TRIỂN VIỆT NAM"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bank for Investment and Development of Vietnam");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BIDV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnHistory.setText("Lịch sử GD");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn3Layout = new javax.swing.GroupLayout(pn3);
        pn3.setLayout(pn3Layout);
        pn3Layout.setHorizontalGroup(
            pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn3Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChangPin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRutTien, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(btnViewBlane, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn3Layout.setVerticalGroup(
            pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRutTien)
                    .addComponent(btnViewBlane))
                .addGap(46, 46, 46)
                .addGroup(pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangPin)
                    .addComponent(btnTransfer))
                .addGap(41, 41, 41)
                .addGroup(pn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnHistory))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        // TODO add your handling code here:
        transfer = new TransferForm(this, rootPaneCheckingEnabled);
        transfer.setVisible(true);
    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnViewBlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBlaneActionPerformed
        // TODO add your handling code here:
        viewBlance();
    }//GEN-LAST:event_btnViewBlaneActionPerformed

    private void btnRutTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutTienActionPerformed
        // TODO add your handling code here:
        withdraw  = new WithDraw(this, rootPaneCheckingEnabled);
        withdraw.setVisible(true);
        
    }//GEN-LAST:event_btnRutTienActionPerformed

    private void btnChangPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangPinActionPerformed
        // TODO add your handling code here:
        changePinDiaLog = new ChangePinDiaLog(this, rootPaneCheckingEnabled);
        changePinDiaLog.setVisible(true);
        
    }//GEN-LAST:event_btnChangPinActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        ViewHistoryTransaction();
    }//GEN-LAST:event_btnHistoryActionPerformed
    private ViewBlance viewblace;
    private BigInteger cardID;
    private String nameBoss;
    private WithDraw withdraw;
    private ChangePinDiaLog changePinDiaLog;
    private TransferForm transfer;
    private  TransactionHistory transactionHistory;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangPin;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnRutTien;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton btnViewBlane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbFullName;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JPanel pn3;
    // End of variables declaration//GEN-END:variables
}
